// Festiwale w Polsce 2026 — dane zebrane 2026-07-30 (research + kalendarze branżowe)
// verified:true  = termin potwierdzony w źródle zebranym podczas researchu
// verified:false = termin orientacyjny (zwykle "zwyczajowy" tydzień roku) — sprawdź na stronie organizatora
// free:true      = wstęp wolny na główną część wydarzenia
// lat/lng        = środek miejscowości (nie dokładny teren festiwalu)
const FESTIWALE = [

  /* ===== MUZYKA ===== */
  { name:"SnowFest Festival", city:"Szczyrk", lat:49.7180, lng:19.0330, start:"2026-03-06", end:"2026-03-07",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Elektronika i hip-hop w scenerii zimowej" },

  { name:"Mystic Festival", city:"Gdańsk", lat:54.3520, lng:18.6466, start:"2026-06-03", end:"2026-06-06",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Metal i hardcore na terenie Stoczni Gdańskiej" },

  { name:"TAURON Nowa Muzyka", city:"Katowice", lat:50.2649, lng:19.0238, start:"2026-06-04", end:"2026-06-07",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Elektronika, jazz, ambient, eksperyment — Strefa Kultury" },

  { name:"LAS Festival", city:"Lubawka", lat:50.6970, lng:16.0000, start:"2026-06-24", end:"2026-06-29",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Elektronika, performance i sztuka w lesie" },

  { name:"Open'er Festival", city:"Gdynia", lat:54.5189, lng:18.5305, start:"2026-07-01", end:"2026-07-04",
    category:"muzyka", free:false, priceMin:null, pricePass:1149, priceNote:"Karnet 4-dniowy 1149 zł",
    website:null, verified:true, note:"Lotnisko Gdynia-Kosakowo; największy polski festiwal wielogatunkowy" },

  { name:"Audioriver Festival", city:"Łódź", lat:51.7592, lng:19.4560, start:"2026-07-10", end:"2026-07-12",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Elektronika; po przeprowadzce z Płocka" },

  { name:"Jarocin Festival", city:"Jarocin", lat:51.9740, lng:17.5060, start:"2026-07-16", end:"2026-07-19",
    category:"muzyka", free:false, priceMin:199, pricePass:null, priceNote:"Bilety jednodniowe od 199 zł",
    website:null, verified:true, note:"Rock alternatywny i polski rock" },

  { name:"Pol'and'Rock Festival", city:"Czaplinek", lat:53.5560, lng:16.2340, start:"2026-07-30", end:"2026-08-01",
    category:"muzyka", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:true, note:"Największa darmowa impreza muzyczna w Polsce (d. Przystanek Woodstock)" },

  { name:"Sunrise Festival", city:"Kołobrzeg", lat:54.1758, lng:15.5830, start:"2026-07-31", end:"2026-08-02",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Elektronika nad morzem" },

  { name:"OFF Festival", city:"Katowice", lat:50.2649, lng:19.0238, start:"2026-08-07", end:"2026-08-09",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Alternatywa i muzyka niezależna, Dolina Trzech Stawów" },

  { name:"BitterSweet Festival", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-08-13", end:"2026-08-15",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Poznańska Cytadela; duże światowe nazwiska" },

  { name:"Wisłoujście Festival", city:"Gdańsk", lat:54.3520, lng:18.6466, start:"2026-08-21", end:"2026-08-23",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Kameralny festiwal w Twierdzy Wisłoujście" },

  { name:"Wratislavia Cantans", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-09-05", end:"2026-09-20",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Część koncertów bezpłatna",
    website:null, verified:false, note:"Oratoria i muzyka chóralna; wrzesień — dokładny termin do potwierdzenia" },

  { name:"Fest Festival", city:"Chorzów", lat:50.2970, lng:18.9540, start:"2026-08-14", end:"2026-08-16",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Park Śląski; termin orientacyjny" },

  { name:"Kraków Live Festival", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-08-21", end:"2026-08-22",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Lotnisko Czyżyny; termin orientacyjny" },

  { name:"Ostróda Reggae Festival", city:"Ostróda", lat:53.6960, lng:19.9650, start:"2026-08-06", end:"2026-08-09",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Największy festiwal reggae w Polsce; termin orientacyjny" },

  { name:"Cieszanów Rock Festiwal", city:"Cieszanów", lat:50.2540, lng:23.1300, start:"2026-08-13", end:"2026-08-16",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Jeden z tańszych karnetów w kraju",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Slot Art Festival", city:"Lubiąż", lat:51.2600, lng:16.4200, start:"2026-07-07", end:"2026-07-11",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Tani karnet z warsztatami w cenie",
    website:null, verified:false, note:"Poklasztorny kompleks w Lubiążu; muzyka + kilkaset warsztatów" },

  { name:"Unsound", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-10-04", end:"2026-10-11",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Muzyka eksperymentalna; termin orientacyjny" },

  { name:"Sacrum Profanum", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-10-09", end:"2026-10-17",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Muzyka współczesna; termin orientacyjny" },

  { name:"Jazz nad Odrą", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-04-18", end:"2026-04-26",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Część wydarzeń w klubach bezpłatna",
    website:null, verified:false, note:"Jeden z najstarszych festiwali jazzowych w Europie; termin orientacyjny" },

  { name:"Chopin i jego Europa", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-08-14", end:"2026-08-31",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Muzyka klasyczna; termin orientacyjny" },

  { name:"Jazz Jamboree", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-10-22", end:"2026-10-25",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Termin orientacyjny" },

  /* ===== FILM ===== */
  { name:"MFF ZOOM–ZBLIŻENIA", city:"Jelenia Góra", lat:50.9044, lng:15.7194, start:"2026-03-02", end:"2026-03-08",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Kino niezależne, dokument, animacja" },

  { name:"Let's Doc", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-03-21", end:"2026-03-28",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Film dokumentalny i edukacja filmowa" },

  { name:"Timeless Film Festival Warsaw", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-04-17", end:"2026-04-27",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Klasyka kina, retrospektywy, spotkania autorskie" },

  { name:"Millennium Docs Against Gravity", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-05-08", end:"2026-05-17",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:"Wersja online 19.05–01.06",
    website:null, verified:true, note:"Równolegle: Wrocław, Gdynia, Poznań, Katowice, Łódź, Bydgoszcz" },

  { name:"Krakowski Festiwal Filmowy", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-05-31", end:"2026-06-07",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Dokument, animacja, film krótkometrażowy" },

  { name:"TAURON Nowe Horyzonty", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-07-23", end:"2026-08-02",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:"Część online do 09.08",
    website:"https://www.nowehoryzonty.pl/", verified:true, note:"Kino artystyczne i eksperymentalne" },

  { name:"EnergaCAMERIMAGE", city:"Toruń", lat:53.0138, lng:18.5984, start:"2026-11-07", end:"2026-11-14",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Światowy festiwal sztuki operatorskiej" },

  { name:"Festiwal Polskich Filmów Fabularnych", city:"Gdynia", lat:54.5189, lng:18.5305, start:"2026-09-14", end:"2026-09-19",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Termin 2026 nie był ogłoszony w momencie zbierania danych" },

  { name:"Warszawski Festiwal Filmowy", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-10-09", end:"2026-10-18",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Mastercard OFF CAMERA", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-04-24", end:"2026-05-03",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Kino niezależne; termin orientacyjny" },

  { name:"Etiuda & Anima", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-11-20", end:"2026-11-27",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Etiudy studenckie i animacja; termin orientacyjny" },

  { name:"Lubuskie Lato Filmowe", city:"Łagów", lat:52.3350, lng:15.3000, start:"2026-06-20", end:"2026-06-27",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Najstarszy festiwal filmowy w Polsce; termin orientacyjny" },

  /* ===== FOLK / TRADYCJA ===== */
  { name:"Festiwal Wszystkie Mazurki Świata", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-04-22", end:"2026-04-25",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Część potańcówek i warsztatów bezpłatna",
    website:null, verified:true, note:"Muzyka tradycyjna, potańcówki wiejskie" },

  { name:"Festiwal Folkowy Polskiego Radia „Nowa Tradycja”", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-05-21", end:"2026-05-24",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Konkurs folkowy Polskiego Radia" },

  { name:"Ogólnopolski Festiwal Kapel i Śpiewaków Ludowych", city:"Kazimierz Dolny", lat:51.3220, lng:21.9520, start:"2026-06-25", end:"2026-06-28",
    category:"folk", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:true, note:"Jubileuszowa 60. edycja; kapele wiejskie z całej Polski" },

  { name:"EtnoBaltica — Festiwal Twórczości Ludowej", city:"Swołowo", lat:54.4667, lng:17.0333, start:"2026-07-03", end:"2026-07-05",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Warsztaty tańca, garncarstwa, EtnoWioska Dziecięca" },

  { name:"Globaltica World Cultures Festival", city:"Gdynia", lat:54.4900, lng:18.5600, start:"2026-07-17", end:"2026-07-19",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Muzyka świata, Park Kolibki w Gdyni Orłowie" },

  { name:"Festiwal Kultury Kresowej", city:"Mrągowo", lat:53.8670, lng:21.3040, start:"2026-08-06", end:"2026-08-09",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Kultura Kresów Wschodnich" },

  { name:"Re:tradycja — Jarmark Jagielloński", city:"Lublin", lat:51.2465, lng:22.5684, start:"2026-08-21", end:"2026-08-23",
    category:"folk", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:true, note:"Targi sztuki ludowej, koncerty, potańcówki, warsztaty na Starym Mieście" },

  { name:"MFF Ziem Górskich", city:"Zakopane", lat:49.2992, lng:19.9496, start:"2026-08-21", end:"2026-08-27",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Międzynarodowy festiwal folkloru ziem górskich" },

  { name:"Pannonica Festival", city:"Stary Sącz", lat:49.5620, lng:20.6350, start:"2026-08-22", end:"2026-08-24",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Muzyka bałkańska, romska i karpacka" },

  { name:"Skrzyżowanie Kultur", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-09-18", end:"2026-09-22",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Muzyka świata; termin orientacyjny (ok. 18–22.09)" },

  { name:"Mikołajki Folkowe", city:"Lublin", lat:51.2465, lng:22.5684, start:"2026-12-11", end:"2026-12-14",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Część wydarzeń bezpłatna",
    website:null, verified:true, note:"Najstarszy festiwal folkowy w Polsce; koncerty i warsztaty" },

  { name:"Festiwal Folkloru Górali Polskich", city:"Żywiec", lat:49.6853, lng:19.1922, start:"2026-08-01", end:"2026-08-05",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Sierpień 2026 — dokładny termin do potwierdzenia" },

  { name:"Tydzień Kultury Beskidzkiej", city:"Wisła", lat:49.6560, lng:18.8600, start:"2026-07-25", end:"2026-08-02",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Wiele koncertów plenerowych bezpłatnych",
    website:null, verified:false, note:"Równolegle Szczyrk, Żywiec, Maków Podhalański; przełom lipca i sierpnia" },

  { name:"Łemkowska Watra", city:"Zdynia", lat:49.5170, lng:21.2670, start:"2026-07-17", end:"2026-07-19",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Kultura łemkowska; III/IV tydzień lipca" },

  { name:"Święto Dzieci Gór", city:"Nowy Sącz", lat:49.6210, lng:20.6970, start:"2026-07-26", end:"2026-08-01",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Korowody i koncerty plenerowe bezpłatne",
    website:null, verified:false, note:"Dziecięce zespoły regionalne; ostatni tydzień lipca" },

  { name:"Folkowisko — Festiwal Kultury Pogranicza", city:"Gorajec", lat:50.2670, lng:23.1500, start:"2026-07-10", end:"2026-07-12",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Tani karnet, klimat wiejskiego podwórka",
    website:null, verified:false, note:"Lipiec 2026 — termin orientacyjny" },

  { name:"MF Piosenki i Kultury Romów", city:"Ciechocinek", lat:52.8800, lng:18.7900, start:"2026-07-17", end:"2026-07-19",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Połowa lipca; termin orientacyjny" },

  { name:"Kurpiowskie Miodobranie", city:"Myszyniec", lat:53.3800, lng:21.3500, start:"2026-09-05", end:"2026-09-06",
    category:"folk", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Tradycje kurpiowskie, bartnictwo; wrzesień" },

  { name:"MF Koronki Klockowej", city:"Bobowa", lat:49.7000, lng:20.9400, start:"2026-10-03", end:"2026-10-04",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Rękodzieło i koronczarstwo; październik" },

  /* ===== HISTORIA / REKONSTRUKCJE ===== */
  { name:"Festiwal Słowian i Wikingów", city:"Wolin", lat:53.8450, lng:14.6120, start:"2026-08-07", end:"2026-08-09",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Największa rekonstrukcja wczesnośredniowieczna w Polsce; I weekend sierpnia" },

  { name:"Dni Grunwaldu", city:"Grunwald", lat:53.4870, lng:20.0870, start:"2026-07-16", end:"2026-07-19",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Inscenizacja bitwy pod Grunwaldem; termin orientacyjny (rocznica 15.07)" },

  { name:"Oblężenie Malborka", city:"Malbork", lat:54.0359, lng:19.0266, start:"2026-07-24", end:"2026-07-26",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Rekonstrukcja oblężenia zamku; termin orientacyjny" },

  { name:"Festyn Archeologiczny w Biskupinie", city:"Biskupin", lat:52.7860, lng:17.7360, start:"2026-09-19", end:"2026-09-27",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Najstarszy festyn archeologiczny w Europie; wrzesień" },

  /* ===== TEATR / SZTUKA ULICY ===== */
  { name:"Malta Festival", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-06-19", end:"2026-06-28",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:"Znaczna część programu plenerowego bezpłatna",
    website:null, verified:false, note:"Teatr, muzyka i sztuka w przestrzeni miasta; termin orientacyjny" },

  { name:"FETA — MF Teatrów Plenerowych i Ulicznych", city:"Gdańsk", lat:54.3520, lng:18.6466, start:"2026-07-09", end:"2026-07-12",
    category:"teatr", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Teatr uliczny na Dolnym Mieście; termin orientacyjny" },

  { name:"Carnaval Sztukmistrzów", city:"Lublin", lat:51.2465, lng:22.5684, start:"2026-07-23", end:"2026-07-26",
    category:"teatr", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Nowy cyrk i sztuka uliczna; termin orientacyjny" },

  { name:"MF Teatrów Ulicznych", city:"Jelenia Góra", lat:50.9044, lng:15.7194, start:"2026-08-27", end:"2026-08-30",
    category:"teatr", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Boska Komedia", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-12-05", end:"2026-12-13",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Przegląd najlepszych polskich spektakli sezonu; termin orientacyjny" },

  { name:"Festiwal Kontakt", city:"Toruń", lat:53.0138, lng:18.5984, start:"2026-05-22", end:"2026-05-29",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Międzynarodowy festiwal teatralny; termin orientacyjny" },

  /* ===== JARMARKI / JEDZENIE ===== */
  { name:"Jarmark św. Dominika", city:"Gdańsk", lat:54.3520, lng:18.6466, start:"2026-07-25", end:"2026-08-16",
    category:"jarmark", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Trzy tygodnie handlu, koncertów i ulicznych scen; termin orientacyjny" },

  { name:"Jarmark Świętojański", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-06-13", end:"2026-06-28",
    category:"jarmark", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Stary Rynek; rękodzieło i jedzenie; termin orientacyjny" },

  { name:"Betlejem Poznańskie (jarmark bożonarodzeniowy)", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-11-27", end:"2026-12-23",
    category:"jarmark", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Jarmark Bożonarodzeniowy na Rynku Głównym", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-11-27", end:"2026-12-26",
    category:"jarmark", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Europejski Festiwal Smaku", city:"Lublin", lat:51.2465, lng:22.5684, start:"2026-09-04", end:"2026-09-06",
    category:"jedzenie", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny, płacisz za jedzenie",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Wrocławski Festiwal Dobrego Piwa", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-06-12", end:"2026-06-14",
    category:"jedzenie", free:false, priceMin:null, pricePass:null, priceNote:"Bilet wstępu + osobno piwo",
    website:null, verified:false, note:"Największy festiwal piw rzemieślniczych w Polsce; termin orientacyjny" },

  { name:"Małopolski Festiwal Smaku", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-08-29", end:"2026-08-30",
    category:"jedzenie", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Finał na Rynku Głównym; termin orientacyjny" },

  /* ===== LITERATURA / IDEE ===== */
  { name:"Big Book Festival", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-06-19", end:"2026-06-21",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:"Część spotkań bezpłatna",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Góry Literatury", city:"Nowa Ruda", lat:50.5800, lng:16.5000, start:"2026-07-09", end:"2026-07-19",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:"Wiele spotkań bezpłatnych",
    website:null, verified:false, note:"Festiwal Olgi Tokarczuk w Kotlinie Kłodzkiej; termin orientacyjny" },

  { name:"Festiwal Conrada", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-10-19", end:"2026-10-25",
    category:"literatura", free:true, priceMin:0, pricePass:0, priceNote:"Większość spotkań bezpłatna",
    website:null, verified:false, note:"Termin orientacyjny" },

  /* ===== INNE / MIEJSKIE ===== */
  { name:"Wianki nad Wisłą", city:"Kraków", lat:50.0647, lng:19.9450, start:"2026-06-20", end:"2026-06-20",
    category:"inne", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, note:"Noc Świętojańska nad Wisłą; termin orientacyjny" },

  { name:"Pyrkon", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-05-15", end:"2026-05-17",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Największy festiwal fantastyki w Polsce, MTP; termin orientacyjny" },

  { name:"Juwenalia", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-05-14", end:"2026-05-17",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:"Pochód i część koncertów bezpłatne",
    website:null, verified:false, note:"Termin orientacyjny" },

  { name:"Festiwal Górski", city:"Lądek-Zdrój", lat:50.3450, lng:16.8800, start:"2026-09-17", end:"2026-09-20",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Filmy i spotkania górskie; termin orientacyjny" }
,

  /* ===== EDYCJE 2027 (oszacowane: +364 dni od edycji 2026, ten sam dzień tygodnia) =====
     Wygenerowane automatycznie, żeby domyślne okno "365 dni od dziś" nie urywało się na Sylwestrze.
     Wszystkie mają estimated:true — w UI dostają badge ~termin. Po ogłoszeniu prawdziwych dat: podmień. */

  { name:"SnowFest Festival", city:"Szczyrk", lat:49.718, lng:19.033, start:"2027-03-05", end:"2027-03-06",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Elektronika i hip-hop w scenerii zimowej" },

  { name:"Mystic Festival", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2027-06-02", end:"2027-06-05",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Metal i hardcore na terenie Stoczni Gdańskiej" },

  { name:"TAURON Nowa Muzyka", city:"Katowice", lat:50.2649, lng:19.0238, start:"2027-06-03", end:"2027-06-06",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Elektronika, jazz, ambient, eksperyment — Strefa Kultury" },

  { name:"LAS Festival", city:"Lubawka", lat:50.697, lng:16, start:"2027-06-23", end:"2027-06-28",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Elektronika, performance i sztuka w lesie" },

  { name:"Open'er Festival", city:"Gdynia", lat:54.5189, lng:18.5305, start:"2027-06-30", end:"2027-07-03",
    category:"muzyka", free:false, priceMin:null, pricePass:1149, priceNote:"Karnet 4-dniowy 1149 zł",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Lotnisko Gdynia-Kosakowo; największy polski festiwal wielogatunkowy" },

  { name:"Audioriver Festival", city:"Łódź", lat:51.7592, lng:19.456, start:"2027-07-09", end:"2027-07-11",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Elektronika; po przeprowadzce z Płocka" },

  { name:"Jarocin Festival", city:"Jarocin", lat:51.974, lng:17.506, start:"2027-07-15", end:"2027-07-18",
    category:"muzyka", free:false, priceMin:199, pricePass:null, priceNote:"Bilety jednodniowe od 199 zł",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Rock alternatywny i polski rock" },

  { name:"Pol'and'Rock Festival", city:"Czaplinek", lat:53.556, lng:16.234, start:"2027-07-29", end:"2027-07-31",
    category:"muzyka", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Największa darmowa impreza muzyczna w Polsce (d. Przystanek Woodstock)" },

  { name:"Sunrise Festival", city:"Kołobrzeg", lat:54.1758, lng:15.583, start:"2027-07-30", end:"2027-08-01",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Elektronika nad morzem" },

  { name:"Slot Art Festival", city:"Lubiąż", lat:51.26, lng:16.42, start:"2027-07-06", end:"2027-07-10",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Tani karnet z warsztatami w cenie",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Poklasztorny kompleks w Lubiążu; muzyka + kilkaset warsztatów" },

  { name:"Jazz nad Odrą", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2027-04-17", end:"2027-04-25",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Część wydarzeń w klubach bezpłatna",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Jeden z najstarszych festiwali jazzowych w Europie; termin orientacyjny" },

  { name:"MFF ZOOM–ZBLIŻENIA", city:"Jelenia Góra", lat:50.9044, lng:15.7194, start:"2027-03-01", end:"2027-03-07",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Kino niezależne, dokument, animacja" },

  { name:"Let's Doc", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-03-20", end:"2027-03-27",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Film dokumentalny i edukacja filmowa" },

  { name:"Timeless Film Festival Warsaw", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-04-16", end:"2027-04-26",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Klasyka kina, retrospektywy, spotkania autorskie" },

  { name:"Millennium Docs Against Gravity", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-05-07", end:"2027-05-16",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:"Wersja online 19.05–01.06",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Równolegle: Wrocław, Gdynia, Poznań, Katowice, Łódź, Bydgoszcz" },

  { name:"Krakowski Festiwal Filmowy", city:"Kraków", lat:50.0647, lng:19.945, start:"2027-05-30", end:"2027-06-06",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Dokument, animacja, film krótkometrażowy" },

  { name:"TAURON Nowe Horyzonty", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2027-07-22", end:"2027-08-01",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:"Część online do 09.08",
    website:"https://www.nowehoryzonty.pl/", verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Kino artystyczne i eksperymentalne" },

  { name:"Mastercard OFF CAMERA", city:"Kraków", lat:50.0647, lng:19.945, start:"2027-04-23", end:"2027-05-02",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Kino niezależne; termin orientacyjny" },

  { name:"Lubuskie Lato Filmowe", city:"Łagów", lat:52.335, lng:15.3, start:"2027-06-19", end:"2027-06-26",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Najstarszy festiwal filmowy w Polsce; termin orientacyjny" },

  { name:"Festiwal Wszystkie Mazurki Świata", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-04-21", end:"2027-04-24",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Część potańcówek i warsztatów bezpłatna",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Muzyka tradycyjna, potańcówki wiejskie" },

  { name:"Festiwal Folkowy Polskiego Radia „Nowa Tradycja”", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-05-20", end:"2027-05-23",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Konkurs folkowy Polskiego Radia" },

  { name:"Ogólnopolski Festiwal Kapel i Śpiewaków Ludowych", city:"Kazimierz Dolny", lat:51.322, lng:21.952, start:"2027-06-24", end:"2027-06-27",
    category:"folk", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Jubileuszowa 60. edycja; kapele wiejskie z całej Polski" },

  { name:"EtnoBaltica — Festiwal Twórczości Ludowej", city:"Swołowo", lat:54.4667, lng:17.0333, start:"2027-07-02", end:"2027-07-04",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Warsztaty tańca, garncarstwa, EtnoWioska Dziecięca" },

  { name:"Globaltica World Cultures Festival", city:"Gdynia", lat:54.49, lng:18.56, start:"2027-07-16", end:"2027-07-18",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Muzyka świata, Park Kolibki w Gdyni Orłowie" },

  { name:"Tydzień Kultury Beskidzkiej", city:"Wisła", lat:49.656, lng:18.86, start:"2027-07-24", end:"2027-08-01",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Wiele koncertów plenerowych bezpłatnych",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Równolegle Szczyrk, Żywiec, Maków Podhalański; przełom lipca i sierpnia" },

  { name:"Łemkowska Watra", city:"Zdynia", lat:49.517, lng:21.267, start:"2027-07-16", end:"2027-07-18",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Kultura łemkowska; III/IV tydzień lipca" },

  { name:"Święto Dzieci Gór", city:"Nowy Sącz", lat:49.621, lng:20.697, start:"2027-07-25", end:"2027-07-31",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Korowody i koncerty plenerowe bezpłatne",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Dziecięce zespoły regionalne; ostatni tydzień lipca" },

  { name:"Folkowisko — Festiwal Kultury Pogranicza", city:"Gorajec", lat:50.267, lng:23.15, start:"2027-07-09", end:"2027-07-11",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:"Tani karnet, klimat wiejskiego podwórka",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Lipiec 2026 — termin orientacyjny" },

  { name:"MF Piosenki i Kultury Romów", city:"Ciechocinek", lat:52.88, lng:18.79, start:"2027-07-16", end:"2027-07-18",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Połowa lipca; termin orientacyjny" },

  { name:"Dni Grunwaldu", city:"Grunwald", lat:53.487, lng:20.087, start:"2027-07-15", end:"2027-07-18",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Inscenizacja bitwy pod Grunwaldem; termin orientacyjny (rocznica 15.07)" },

  { name:"Oblężenie Malborka", city:"Malbork", lat:54.0359, lng:19.0266, start:"2027-07-23", end:"2027-07-25",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Rekonstrukcja oblężenia zamku; termin orientacyjny" },

  { name:"Malta Festival", city:"Poznań", lat:52.4064, lng:16.9252, start:"2027-06-18", end:"2027-06-27",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:"Znaczna część programu plenerowego bezpłatna",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Teatr, muzyka i sztuka w przestrzeni miasta; termin orientacyjny" },

  { name:"FETA — MF Teatrów Plenerowych i Ulicznych", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2027-07-08", end:"2027-07-11",
    category:"teatr", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Teatr uliczny na Dolnym Mieście; termin orientacyjny" },

  { name:"Carnaval Sztukmistrzów", city:"Lublin", lat:51.2465, lng:22.5684, start:"2027-07-22", end:"2027-07-25",
    category:"teatr", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Nowy cyrk i sztuka uliczna; termin orientacyjny" },

  { name:"Festiwal Kontakt", city:"Toruń", lat:53.0138, lng:18.5984, start:"2027-05-21", end:"2027-05-28",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Międzynarodowy festiwal teatralny; termin orientacyjny" },

  { name:"Jarmark św. Dominika", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2027-07-24", end:"2027-08-15",
    category:"jarmark", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Trzy tygodnie handlu, koncertów i ulicznych scen; termin orientacyjny" },

  { name:"Jarmark Świętojański", city:"Poznań", lat:52.4064, lng:16.9252, start:"2027-06-12", end:"2027-06-27",
    category:"jarmark", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Stary Rynek; rękodzieło i jedzenie; termin orientacyjny" },

  { name:"Wrocławski Festiwal Dobrego Piwa", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2027-06-11", end:"2027-06-13",
    category:"jedzenie", free:false, priceMin:null, pricePass:null, priceNote:"Bilet wstępu + osobno piwo",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Największy festiwal piw rzemieślniczych w Polsce; termin orientacyjny" },

  { name:"Big Book Festival", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-06-18", end:"2027-06-20",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:"Część spotkań bezpłatna",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Termin orientacyjny" },

  { name:"Góry Literatury", city:"Nowa Ruda", lat:50.58, lng:16.5, start:"2027-07-08", end:"2027-07-18",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:"Wiele spotkań bezpłatnych",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Festiwal Olgi Tokarczuk w Kotlinie Kłodzkiej; termin orientacyjny" },

  { name:"Wianki nad Wisłą", city:"Kraków", lat:50.0647, lng:19.945, start:"2027-06-19", end:"2027-06-19",
    category:"inne", free:true, priceMin:0, pricePass:0, priceNote:"Wstęp wolny",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Noc Świętojańska nad Wisłą; termin orientacyjny" },

  { name:"Pyrkon", city:"Poznań", lat:52.4064, lng:16.9252, start:"2027-05-14", end:"2027-05-16",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Największy festiwal fantastyki w Polsce, MTP; termin orientacyjny" },

  { name:"Juwenalia", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2027-05-13", end:"2027-05-16",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:"Pochód i część koncertów bezpłatne",
    website:null, verified:false, estimated:true, note:"Edycja 2027 — termin oszacowany jako ten sam tydzień co w 2026; potwierdź u organizatora. Termin orientacyjny" },


  /* ===== MUZYKA — rozszerzenie 2026-07-30 (research) ===== */
  { name:"Summer Jazz Festival Kraków", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-06-27", end:"2026-08-31",
    category:"muzyka", free:false, priceMin:53, pricePass:null, priceNote:"Bilety na pojedyncze koncerty od ok. 50 zł",
    website:"https://www.summerjazz.pl/", verified:true, note:"Jubileuszowa 31. edycja najstarszego krakowskiego festiwalu jazzowego, ok. 150 koncertów w klubach całego miasta." },
  { name:"Jazz na Starówce", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-07-04", end:"2026-08-29",
    category:"muzyka", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.jazznastarowce.pl/", verified:true, note:"32. plenerowy festiwal jazzowy na Rynku Starego Miasta, koncerty w każdą letnią sobotę, wstęp wolny." },
  { name:"Summer Contrast Festival", city:"Rogalinko", lat:53.8089, lng:15.8435, start:"2026-08-04", end:"2026-08-10",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://summercontrast.org/", verified:true, note:"Tygodniowy festiwal elektroniki i psytrance'u łączący nocne techno z porannym ambientem na łąkach Rogalinka." },
  { name:"Męskie Granie", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-08-07", end:"2026-08-08",
    category:"muzyka", free:false, priceMin:483, pricePass:null, priceNote:"Karnet 2-dniowy od 483 zł",
    website:"https://meskiegranie.pl/", verified:true, note:"Trasa 2026 przez Żywiec, Poznań, Wrocław i Kraków; finałowa edycja na terenie Muzeum Lotnictwa Polskiego." },
  { name:"Santander Letnie Brzmienia", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-08-07", end:"2026-08-08",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://alterart.pl/", verified:true, note:"Letnia trasa festiwalowa Alter Art przez 5 miast; po Warszawie edycje w Gdańsku (21–22.08), Wrocławiu (28–29.08) i Poznaniu (4–5.09)." },
  { name:"Rockowizna Festiwal", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-08-07", end:"2026-08-08",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://rockowizna.pl", verified:true, note:"5. edycja trasy rockowej z headlinerem Sex Pistols; termin potwierdzony dla Gdańska (Polsat Plus Arena), Poznań i Kraków później w sierpniu." },
  { name:"Solidarity of Arts", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-08-08", end:"2026-09-02",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Część wydarzeń bezpłatna",
    website:"https://www.gdansk.pl/wydarzenia/solidarity-of-arts,w,19261", verified:true, note:"Festiwal ECS z muzyką poważną i jazzem, inauguruje go koncert Maksima Vengerova." },
  { name:"Olsztyn Green Festival", city:"Olsztyn", lat:53.7766, lng:20.4778, start:"2026-08-14", end:"2026-08-16",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.ebilet.pl/muzyka/festiwale/olsztyn-green-festival", verified:true, note:"Duży plenerowy festiwal nad jeziorem Ukiel z trzema scenami i polskimi gwiazdami pop-rocka." },
  { name:"TOP of the TOP Sopot Festival", city:"Sopot", lat:54.443, lng:18.5613, start:"2026-08-24", end:"2026-08-25",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.topofthetop.pl", verified:true, note:"Cykl koncertów w Operze Leśnej z transmisją TVN, m.in. „Top of the Pop” i koncert Stanisława Soyki." },
  { name:"Summer Fall Festival", city:"Płock", lat:52.5353, lng:19.7136, start:"2026-08-28", end:"2026-08-29",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.ticketmaster.pl", verified:true, note:"Dwudniowy festiwal rockowo-popowy w płockim amfiteatrze." },
  { name:"Summer Dying Loud", city:"Aleksandrów Łódzki", lat:51.8197, lng:19.3035, start:"2026-09-03", end:"2026-09-05",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://summerdyingloud.pl/", verified:true, note:"XVII edycja festiwalu metalowego z trzydniowym line-upem na stadionie MOSiR." },
  { name:"Muzyka na Szczytach", city:"Zakopane", lat:49.2992, lng:19.9496, start:"2026-09-05", end:"2026-09-13",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"XVIII festiwal muzyki klasycznej; dzień inauguracyjny 5 września 2026 potwierdził Urząd Miasta Zakopane, pełny zakres dat przybliżony." },
  { name:"Great September Showcase Festival & Conference", city:"Łódź", lat:51.7592, lng:19.456, start:"2026-09-10", end:"2026-09-12",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://greatseptember.pl/", verified:true, note:"Najważniejszy polski festiwal showcase'owy z koncertami w klubach centrum Łodzi i konferencją branżową." },
  { name:"Warszawska Jesień", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-09-18", end:"2026-09-26",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://warszawska-jesien.art.pl/", verified:true, note:"Najstarszy i największy w Polsce międzynarodowy festiwal muzyki współczesnej." },
  { name:"Rawa Blues Festival", city:"Katowice", lat:50.2649, lng:19.0238, start:"2026-10-03", end:"2026-10-03",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://rawablues.com/", verified:true, note:"44. edycja najstarszego i najbardziej prestiżowego festiwalu bluesowego w Polsce." },
  { name:"Komeda Jazz Festival", city:"Słupsk", lat:54.4636, lng:17.0209, start:"2026-10-09", end:"2026-11-05",
    category:"muzyka", free:false, priceMin:250, pricePass:null, priceNote:"Bilety na koncert finałowy od 250 zł",
    website:"https://komedajazz.com/", verified:true, note:"XXXII edycja festiwalu poświęconego muzyce na pograniczu jazzu, soulu i bluesa, koncerty rozłożone od października do listopada." },
  { name:"Jazz Jantar", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-10-21", end:"2026-10-25",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://jazzjantar.pl/", verified:true, note:"Jesienna odsłona gdańskiego festiwalu jazzowego w Klubie Żak; edycja wiosenna odbyła się 25–29 marca 2026." },
  { name:"Soundedit", city:"Łódź", lat:51.7592, lng:19.456, start:"2026-10-23", end:"2026-10-25",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://soundedit.pl/", verified:true, note:"Międzynarodowy Festiwal Producentów Muzycznych z koncertami i galą Człowiek ze Złotym Uchem." },
  { name:"Mayday Poland", city:"Katowice", lat:50.2649, lng:19.0238, start:"2026-11-10", end:"2026-11-10",
    category:"muzyka", free:false, priceMin:359, pricePass:null, priceNote:null,
    website:"https://sklep.mayday.pl/", verified:true, note:"Kultowa impreza muzyki elektronicznej w Spodku, w 2026 pod hasłem „ICONIC”." },
  { name:"Festiwal Eufonie", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-11-12", end:"2026-12-06",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.eufonie.pl/", verified:true, note:"8. Międzynarodowy Festiwal Muzyki Europy Środkowo-Wschodniej, koncerty w Warszawie i kilkunastu miastach Polski." },
  { name:"Inside Seaside", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-11-13", end:"2026-11-14",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://insideseaside.pl/", verified:true, note:"Halowy jesienny festiwal w AmberExpo z zagranicznymi gwiazdami indie i alternatywy." },
  { name:"Jazztopad Festival", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-11-13", end:"2026-11-22",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.nfm.wroclaw.pl/festiwale/jazztopad-festival", verified:true, note:"Festiwal jazzu improwizowanego w NFM z prawykonaniami zamówionych kompozycji, koncerty w dwóch weekendowych blokach." },
  { name:"Cavatina Guitar Festival", city:"Bielsko-Biała", lat:49.8121, lng:19.0292, start:"2027-05-22", end:"2027-05-23",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://cavatinaguitarfestival.com/", verified:false, estimated:true, note:"Festiwal gitarowy w Cavatina Hall; edycja 2026 odbyła się 23–24 maja, termin 2027 to szacunek." },
  { name:"Up To Date Festival", city:"Białystok", lat:53.1275, lng:23.1471, start:"2027-05-27", end:"2027-05-29",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://uptodate.pl/", verified:false, estimated:true, note:"Ceniony festiwal elektroniki klubowej i eksperymentalnej; edycja 2026 odbyła się 28–30 maja, termin 2027 to szacunek." },
  { name:"Enter Enea Festival", city:"Poznań", lat:52.4064, lng:16.9252, start:"2027-05-30", end:"2027-06-02",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:"Część dni z bezpłatnym wstępem",
    website:"https://entereneafestival.pl/", verified:false, estimated:true, note:"Jazzowy festiwal nad Jeziorem Strzeszyńskim; edycja 2026 odbyła się 31.05–3.06, termin 2027 to szacunek." },
  { name:"Instytut Festival", city:"Nowy Dwór Mazowiecki", lat:52.4342, lng:20.7061, start:"2027-06-18", end:"2027-06-20",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.ebilet.pl/muzyka/festiwale/instytut-festival", verified:false, estimated:true, note:"Techno-festiwal w XIX-wiecznym Garnizonie Modlin; edycja 2026 potwierdzona, ale dokładny termin 2027 to szacunek na czerwiec." },
  { name:"Wschód Kultury – Inne Brzmienia", city:"Lublin", lat:51.2465, lng:22.5684, start:"2027-07-01", end:"2027-07-04",
    category:"muzyka", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://innebrzmienia.eu/", verified:false, estimated:true, note:"Bezpłatny festiwal muzyki nieoczywistej; edycja 2026 odbyła się 2–5 lipca, termin 2027 to szacunek." },
  { name:"Polish Hip-Hop Festival", city:"Płock", lat:52.5353, lng:19.7136, start:"2027-07-01", end:"2027-07-03",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, estimated:true, note:"Największy polski festiwal hip-hopowy na plaży nad Wisłą; edycja 2026 odbyła się 2–4 lipca, termin 2027 to szacunek." },
  { name:"Warsaw Summer Jazz Days", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-07-01", end:"2027-07-04",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.stodola.pl/", verified:false, estimated:true, note:"Klasyczny festiwal jazzowy w klubie Stodoła; 35. edycja odbyła się 2–5 lipca 2026, termin 2027 to szacunek." },
  { name:"Rock na Bagnie", city:"Goniądz", lat:53.4892, lng:22.7324, start:"2027-07-02", end:"2027-07-03",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://rocknabagnie.pl/", verified:false, estimated:true, note:"Niezależny festiwal punk/ska/hardcore nad Biebrzą; edycja 2026 odbyła się 3–4 lipca, termin 2027 to szacunek." },
  { name:"Castle Party Festival", city:"Bolków", lat:50.922, lng:16.1005, start:"2027-07-15", end:"2027-07-18",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://castleparty.com/", verified:false, estimated:true, note:"Największy festiwal gotycki w Europie Środkowej na zamku w Bolkowie; edycja 2026 odbyła się 16–19 lipca, termin 2027 to szacunek." },
  { name:"Blue Summer Jazz Festival", city:"Poznań", lat:52.4064, lng:16.9252, start:"2027-07-17", end:"2027-07-18",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://bluesummerjazz.pl/", verified:false, estimated:true, note:"Kameralny plenerowy festiwal poznańskiego Blue Note w Parku Starego Browaru; edycja 2026 odbyła się 18–19 lipca, termin 2027 to szacunek." },
  { name:"Ladies' Jazz Festival", city:"Gdynia", lat:54.49, lng:18.56, start:"2027-07-19", end:"2027-07-25",
    category:"muzyka", free:false, priceMin:234, pricePass:null, priceNote:"Bilety na koncerty galowe 234–349 zł (2026)",
    website:"https://www.ladiesjazz.pl/", verified:false, estimated:true, note:"Festiwal kobiet jazzu w Gdyni i Wejherowie; 22. edycja odbyła się 20–26 lipca 2026, termin 2027 to szacunek." },
  { name:"Muse Festival", city:"Kawęczyn", lat:51.9409, lng:20.9065, start:"2027-07-23", end:"2027-07-25",
    category:"muzyka", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://musefestival.org/", verified:false, estimated:true, note:"Festiwal muzyki elektronicznej w pałacu Balzaq Palace; edycja 2026 odbyła się 24–26 lipca, termin 2027 to szacunek." },
  { name:"Łódź Summer Festival", city:"Łódź", lat:51.7592, lng:19.456, start:"2027-07-23", end:"2027-07-25",
    category:"muzyka", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.lodzsummerfestival.pl/", verified:false, estimated:true, note:"Największy bezpłatny miejski festiwal w Polsce na Błoniach Łódzkich; edycja 2026 odbyła się 24–26 lipca, termin 2027 to szacunek." },

  /* ===== FILM — rozszerzenie 2026-07-30 (research) ===== */
  { name:"20. BNP Paribas Festiwal Filmu i Sztuki Dwa Brzegi", city:"Kazimierz Dolny", lat:51.322, lng:21.952, start:"2026-08-01", end:"2026-08-09",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://dwabrzegi.pl", verified:true, note:"Jubileuszowa edycja kameralnego festiwalu kina i sztuki nad Wisłą." },
  { name:"Festiwal Filmu i Sztuki BNP Paribas Dwa Brzegi", city:"Kazimierz Dolny", lat:51.322, lng:21.952, start:"2026-08-01", end:"2026-08-08",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://dwabrzegi.pl", verified:true, note:"Jubileuszowa 20. edycja festiwalu kina i sztuki nad Wisłą z koncertami i spotkaniami z twórcami." },
  { name:"Festiwal Filmowy Kino Dzieci", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-09-26", end:"2026-10-04",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:"Bilet seansu zwykle ok. 12–15 zł",
    website:"https://kinodzieci.pl", verified:false, note:"Ogólnopolski festiwal filmów dla dzieci w ok. 20 kinach; termin szacowany na przełom września i października jak w poprzednich latach." },
  { name:"18. Festiwal Filmowy NNW (Niepokorni, Niezłomni, Wyklęci)", city:"Gdynia", lat:54.49, lng:18.56, start:"2026-10-01", end:"2026-10-04",
    category:"film", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://festiwalnnw.pl", verified:true, note:"Festiwal IPN poświęcony historii Polski XX wieku; część wydarzeń w Gdańsku." },
  { name:"12. Festiwal Filmowy Spektrum", city:"Świdnica", lat:50.8425, lng:16.4871, start:"2026-10-20", end:"2026-10-25",
    category:"film", free:true, priceMin:null, pricePass:null, priceNote:"Większość pokazów z bezpłatnymi wejściówkami",
    website:"https://spektrumfestiwal.pl", verified:true, note:"Festiwal kina niezależnego w Świdnicy z pokazami także w czeskim Trutnovie." },
  { name:"Splat!FilmFest 2026", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-10-22", end:"2026-10-31",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://splatfilmfest.com", verified:true, note:"Międzynarodowy festiwal kina gatunkowego: horrory, thrillery i czarne komedie." },
  { name:"20. Festiwal Filmów Azjatyckich Pięć Smaków", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-11-10", end:"2026-11-17",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.piecsmakow.pl", verified:true, note:"Jubileuszowa 20. edycja jedynego polskiego festiwalu poświęconego wyłącznie kinu Azji; repliki m.in. w Poznaniu." },
  { name:"17. TAURON American Film Festival", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-11-17", end:"2026-11-22",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.americanfilmfestival.pl", verified:true, note:"Festiwal kina niezależnego z USA w Kinie Nowe Horyzonty, z sekcją branżową U.S. in Progress." },
  { name:"14. Festiwal Filmów Rosyjskich „Sputnik nad Polską”", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-11-20", end:"2026-11-29",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"Termin szacowany na drugą połowę listopada 2026 na podstawie dotychczasowych edycji (13. edycja: 21.11–1.12.2025)." },
  { name:"44. MFF dla Młodej Widowni Ale Kino!", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-11-22", end:"2026-11-29",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://alekino.com", verified:true, note:"Festiwal filmów dla dzieci i młodzieży z konkursami ocenianymi przez młodych jurorów." },
  { name:"LGBT+ Film Festival", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-11-30", end:"2026-12-12",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://lgbtfilmfest.pl", verified:false, note:"Według kalendarium PISF edycja 2026 w Gdańsku 30.11–6.12 i w Warszawie 11–12.12; pełne daty dla wszystkich miast do potwierdzenia." },
  { name:"20. MFF Krótkometrażowych Żubroffka", city:"Białystok", lat:53.1275, lng:23.1471, start:"2026-12-02", end:"2026-12-06",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.zubroffka.pl", verified:true, note:"Jubileuszowa 20. edycja festiwalu krótkiego metrażu w Białymstoku i na Podlasiu." },
  { name:"26. MFF WATCH DOCS. Prawa Człowieka w Filmie", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-12-04", end:"2026-12-13",
    category:"film", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://watchdocs.pl", verified:true, note:"Najstarszy polski festiwal filmów o prawach człowieka, w kinach i online w całej Polsce." },
  { name:"Ogólnopolski Festiwal Animacji O!PLA", city:"Kraków", lat:50.0647, lng:19.945, start:"2027-03-20", end:"2027-04-30",
    category:"film", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://opla.pl", verified:false, estimated:true, note:"Niezależny festiwal polskiej animacji odbywający się wiosną w wielu miejscowościach w Polsce, edycja 2026 już minęła." },

  /* ===== FOLK — rozszerzenie 2026-07-30 (research) ===== */
  { name:"49. Międzynarodowy Jarmark Folkloru", city:"Węgorzewo", lat:54.2138, lng:21.7417, start:"2026-08-01", end:"2026-08-02",
    category:"folk", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.muzeum-wegorzewo.pl/", verified:true, note:"Największa impreza folklorystyczna Polski północno-wschodniej, kontynuująca tradycję Krainy Trzech Kultur." },
  { name:"Światowy Festiwal Polskich Zespołów Ludowych", city:"Bobowa", lat:49.7, lng:20.94, start:"2026-08-06", end:"2026-08-09",
    category:"folk", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Festiwal folkloru i koronki klockowej organizowany przez WCK w Bobowej." },
  { name:"Pieśń Naszych Korzeni", city:"Jarosław", lat:50.0159, lng:22.6797, start:"2026-08-16", end:"2026-08-23",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://piesnnaszychkorzeni.pl/", verified:true, note:"Festiwal muzyki dawnej i tradycyjnej z koncertami i potańcówkami w zabytkowej przestrzeni Jarosławia." },
  { name:"Romane Dyvesa", city:"Gorzów Wielkopolski", lat:52.731, lng:15.24, start:"2026-08-21", end:"2026-08-21",
    category:"folk", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://terno.com.pl/", verified:true, note:"XXXVIII Międzynarodowe Spotkania Zespołów Cygańskich — najstarszy festiwal kultury romskiej w Polsce." },
  { name:"Kraków Celtic Festival", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-09-04", end:"2026-09-06",
    category:"folk", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://krakowcelticfestival.pl", verified:true, note:"Bezpłatny festiwal muzyki i tańca celtyckiego w Dworku Białoprądnickim." },

  /* ===== HISTORIA — rozszerzenie 2026-07-30 (research) ===== */
  { name:"XXXI Festiwal Słowian i Wikingów", city:"Wolin", lat:53.845, lng:14.612, start:"2026-07-30", end:"2026-08-02",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:"Bilet na teren skansenu (Wyspa Ostrów) płatny; część gminna na Błoniach bezpłatna",
    website:"https://festiwal.jomsborg-vineta.com/", verified:true, note:"Jeden z największych w Europie zjazdów rekonstruktorów wczesnego średniowiecza, edycja 2026 pod hasłem „Wierzenia Słowian”." },
  { name:"XXIII Turniej Rycerski o Pierścień Księżnej Anny", city:"Liw", lat:52.375, lng:21.9671, start:"2026-08-08", end:"2026-08-08",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://turniejerycerskie.pl/wydarzenie/xxiii-turniej-rycerski-o-piercie-ksinej-anny-na-zamku-w-liwie/", verified:true, note:"Jednodniowy turniej rycerski z pokazami konnymi na zamku w Liwie." },
  { name:"XXV Festiwal Historyczny Vivat Vasa", city:"Gniew", lat:53.8342, lng:18.8252, start:"2026-08-14", end:"2026-08-16",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://vivatvasa.pl/", verified:true, note:"Jubileuszowa edycja w 400. rocznicę bitwy pod Gniewem 1626, z turniejem husarskim 15 sierpnia." },
  { name:"Złoto Gór Salzburskich", city:"Złoty Stok", lat:50.4429, lng:16.8747, start:"2026-08-15", end:"2026-08-16",
    category:"historia", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://zlotystok.pl/", verified:false, note:"Górnicze święto z orszakiem, turniejem i jarmarkiem nawiązujące do wydobycia złota; termin przybliżony — zwykle połowa sierpnia." },
  { name:"D-Day Hel", city:"Hel", lat:54.6237, lng:18.7275, start:"2026-08-16", end:"2026-08-23",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Jubileuszowa XX edycja wielkiej inscenizacji militarnej z rekonstruktorami z całej Europy." },
  { name:"XXXI Festyn Archeologiczny w Biskupinie", city:"Biskupin", lat:52.786, lng:17.736, start:"2026-09-12", end:"2026-09-16",
    category:"historia", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://muzeum.biskupin.pl/", verified:true, note:"Największa w Polsce impreza archeologiczno-rekonstrukcyjna, w trzecim tygodniu września w rezerwacie biskupińskim." },

  /* ===== TEATR — rozszerzenie 2026-07-30 (research) ===== */
  { name:"Festiwal Szekspirowski", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-07-23", end:"2026-08-02",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://festiwalszekspirowski.pl", verified:true, note:"30. edycja międzynarodowego festiwalu teatralnego poświęconego twórczości Szekspira." },
  { name:"Olsztyńskie Spotkania Teatralne", city:"Olsztyn", lat:53.7766, lng:20.4778, start:"2026-09-03", end:"2026-09-13",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://teatr.olsztyn.pl", verified:true, note:"31. edycja festiwalu w Teatrze im. Jaracza, druga część 5-8 listopada 2026." },
  { name:"Festiwal Łódź Wielu Kultur", city:"Łódź", lat:51.7592, lng:19.456, start:"2026-09-17", end:"2026-09-20",
    category:"teatr", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://lodzwielukultur.pl", verified:true, note:"Festiwal kroczący od maja do listopada z głównym weekendem wydarzeń 17-20 września." },
  { name:"Festiwal Prapremier", city:"Bydgoszcz", lat:53.1297, lng:18.0294, start:"2026-10-16", end:"2026-10-30",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://festiwalprapremier.pl", verified:true, note:"Jubileuszowa 25. edycja festiwalu prezentującego najnowsze premiery polskich teatrów." },
  { name:"Kaliskie Spotkania Teatralne – Festiwal Sztuki Aktorskiej", city:"Kalisz", lat:51.7473, lng:18.0795, start:"2027-04-17", end:"2027-05-16",
    category:"teatr", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://teatr.kalisz.pl/kst/", verified:false, estimated:true, note:"Edycja 2026 już się odbyła (18.04-16.05), termin 2027 przybliżony na podstawie poprzednich edycji." },

  /* ===== LITERATURA — rozszerzenie 2026-07-30 (research) ===== */
  { name:"Plener Literacki", city:"Gdynia", lat:54.49, lng:18.56, start:"2026-07-31", end:"2026-08-02",
    category:"literatura", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Nadmorski plener literacki na Bulwarze im. Feliksa Nowowiejskiego." },
  { name:"Literacki Sopot", city:"Sopot", lat:54.443, lng:18.5613, start:"2026-08-20", end:"2026-08-23",
    category:"literatura", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://literackisopot.pl", verified:true, note:"15. edycja międzynarodowego festiwalu literackiego, tym razem poświęcona literaturze portugalskojęzycznej." },
  { name:"Festiwal Rzeki Literatury", city:"Zielona Góra", lat:51.9276, lng:15.549, start:"2026-08-20", end:"2026-08-23",
    category:"literatura", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Sierpniowy festiwal literacki z cyklu wydarzeń książkowych nad Odrą." },
  { name:"Gdańskie Targi Książki", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-09-11", end:"2026-09-13",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Jesienne targi książki ze spotkaniami autorskimi i wydarzeniami towarzyszącymi." },
  { name:"Międzynarodowe Targi Książki w Krakowie", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-10-22", end:"2026-10-25",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.ksiazka.krakow.pl", verified:true, note:"27. edycja największych targów książki w Małopolsce." },
  { name:"Targi Książki w Katowicach", city:"Katowice", lat:50.2649, lng:19.0238, start:"2026-11-06", end:"2026-11-08",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://targi-ksiazki.pl", verified:true, note:"Duże regionalne targi książkowe z rozbudowanym programem spotkań." },
  { name:"Toruński Festiwal Książki", city:"Toruń", lat:53.0138, lng:18.5984, start:"2026-11-13", end:"2026-11-15",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:false, note:"32. edycja festiwalu książki zaplanowana na listopad 2026, dokładny termin przybliżony." },
  { name:"Festiwal Literatury dla Dzieci", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-11-24", end:"2026-11-29",
    category:"literatura", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://fldd.pl", verified:true, note:"13. edycja ogólnopolskiego festiwalu literatury dla najmłodszych czytelników." },
  { name:"Targi Książki Historycznej", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-11-26", end:"2026-11-29",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://tkh.org.pl", verified:true, note:"XXXIII edycja najważniejszego w Polsce wydarzenia poświęconego książce historycznej, na Zamku Królewskim." },
  { name:"Wrocławskie Targi Dobrych Książek", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-12-04", end:"2026-12-06",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://targiksiazek.pl", verified:true, note:"34. edycja grudniowych targów książki w Hali Stulecia." },
  { name:"Warszawskie Targi Książki", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2027-05-27", end:"2027-05-30",
    category:"literatura", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://targi-ksiazki.pl/warszawa", verified:false, estimated:true, note:"Edycja 2026 odbyła się 28-31 maja na PGE Narodowym, termin 2027 przybliżony." },

  /* ===== JEDZENIE — rozszerzenie 2026-07-30 (research) ===== */
  { name:"Wrocławska Feta – Festiwal Piwa, Wina i Sera", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-08-07", end:"2026-08-09",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://pik.wroclaw.pl/wroclawska-feta-festiwal/", verified:true, note:"Letnia edycja degustacyjnego festiwalu rzemieślniczego piwa, wina i serów na wrocławskim Rynku." },
  { name:"Festiwal Sera na Skolnitym", city:"Bielsko-Biała", lat:49.8121, lng:19.0292, start:"2026-08-08", end:"2026-08-09",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://pskbb.slaskie.travel/event/1030939/ix-festiwal-sera-na-skolnitym", verified:true, note:"IX edycja festiwalu wiślańskiej tradycji serowarskiej z degustacjami i koncertami." },
  { name:"Krakowski Festiwal Pierogów", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-08-12", end:"2026-08-16",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://pik.krakow.pl/festiwal-pierogow-na-malym-rynku/", verified:true, note:"24. edycja festiwalu na Małym Rynku z konkursem na najlepsze pierogi wokół 15 sierpnia." },
  { name:"Chmielaki Krasnostawskie", city:"Krasnystaw", lat:50.983, lng:23.1698, start:"2026-08-21", end:"2026-08-23",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://chmielaki.pl", verified:true, note:"Najstarszy festiwal piwny w Polsce – 55. Ogólnopolskie Święto Chmielarzy i Piwowarów z darmowymi koncertami." },
  { name:"Ogólnopolski Festiwal Dobrego Smaku", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-08-21", end:"2026-08-23",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://ofds.pl", verified:true, note:"20. edycja jednej z najważniejszych imprez kulinarnych w Polsce na Placu Wolności w Poznaniu." },
  { name:"Gastro Miasto Wrocław", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-08-21", end:"2026-08-23",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.wroclaw.pl/dla-mieszkanca/sanah-mrozu-festiwale-koncerty-wydarzenia-we-wroclawiu-w-2026-roku", verified:true, note:"Cykliczny festiwal food trucków i restauracji na Bulwarze Dunikowskiego, piąta edycja sezonu 2026." },
  { name:"Międzynarodowe Dni Wina", city:"Jasło", lat:49.747, lng:21.4936, start:"2026-08-28", end:"2026-08-30",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.dniwina.pl", verified:true, note:"Duży festiwal winiarski na Podkarpaciu z degustacjami win z całego regionu i koncertami." },
  { name:"Gastro Miasto Kraków", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-08-28", end:"2026-08-30",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://krakow.pl/aktualnosci/319032,31,komunikat,gastro_miasto_krakow.html", verified:true, note:"Największy festiwal kulinarny w Polsce – ostatnia z czterech edycji sezonu na Bulwarze Czerwieńskim pod Wawelem." },
  { name:"Winobranie", city:"Zielona Góra", lat:51.9276, lng:15.549, start:"2026-09-04", end:"2026-09-12",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://winobranie.zgora.pl", verified:true, note:"Największe święto wina w Polsce – dziewięć dni jarmarku, koncertów i degustacji w centrum Zielonej Góry." },
  { name:"Festiwal Jabłka w Grójcu", city:"Grójec", lat:51.8655, lng:20.8675, start:"2026-09-19", end:"2026-09-19",
    category:"jedzenie", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://grojecmiasto.pl/wydarzenia/7087/festiwal-jablka", verified:false, note:"Przybliżony termin w trzecią sobotę września – święto grójeckich jabłek z paradą i degustacjami." },
  { name:"Warszawski Festiwal Piwa (edycja jesienna)", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-10-15", end:"2026-10-17",
    category:"jedzenie", free:false, priceMin:null, pricePass:null, priceNote:"Bilety jednodniowe, zwykle od ok. 50 zł",
    website:"https://warszawskifestiwalpiwa.pl", verified:true, note:"Największy festiwal piwa rzemieślniczego w Polsce, jesienna edycja na Stadionie Legii." },
  { name:"Poznańskie Targi Piwne", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-11-13", end:"2026-11-15",
    category:"jedzenie", free:false, priceMin:null, pricePass:null, priceNote:"Bilety jednodniowe i karnety w przedsprzedaży",
    website:"https://poznanskietargipiwne.pl", verified:false, note:"Przybliżony termin w połowie listopada – duży festiwal z udziałem kilkudziesięciu browarów na terenie MTP." },
  { name:"Beer Geek Madness 2027", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2027-04-23", end:"2027-04-24",
    category:"jedzenie", free:false, priceMin:null, pricePass:null, priceNote:"Bilety jednodniowe w przedsprzedaży na Ticketmaster",
    website:"https://beergeekmadness.pl", verified:true, note:"Najbardziej międzynarodowy festiwal piwa kraftowego w Polsce, organizowany przez Browar Stu Mostów w Czasoprzestrzeni." },

  /* ===== JARMARK — rozszerzenie 2026-07-30 (research) ===== */
  { name:"Jarmark Podhalański", city:"Nowy Targ", lat:49.4892, lng:20.0263, start:"2026-08-14", end:"2026-08-16",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Jubileuszowy 24. jarmark z rękodziełem i strefą rodzinną w roku obchodów 680-lecia lokacji Nowego Targu." },
  { name:"Jarmark Cysterski", city:"Pelplin", lat:53.9283, lng:18.6978, start:"2026-09-18", end:"2026-09-20",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://jarmarkcysterski.diecezja-pelplin.pl", verified:true, note:"XXV edycja dużego jarmarku historyczno-rzemieślniczego przy katedrze w Pelplinie." },
  { name:"Jarmark Bożonarodzeniowy w Gdańsku", city:"Gdańsk", lat:54.352, lng:18.6466, start:"2026-11-20", end:"2026-12-23",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://bozonarodzeniowy.pl", verified:true, note:"Wielokrotnie wybierany najpiękniejszym jarmarkiem świątecznym w Europie – Targ Węglowy i strefy w Głównym Mieście." },
  { name:"Jarmark Bożonarodzeniowy we Wrocławiu", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2026-11-20", end:"2027-01-06",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://www.wroclaw.pl", verified:false, note:"Przybliżony termin na wzór edycji 2025/26 (od ok. 21 listopada do początku stycznia) na Rynku i Placu Solnym; daty 2026 jeszcze nieogłoszone." },
  { name:"Jarmark Bożonarodzeniowy na Starym Mieście", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-11-20", end:"2027-01-06",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://go2warsaw.pl/events/jarmark-bozonarodzeniowy-przy-barbakanie/", verified:false, note:"Przybliżony termin na wzór poprzednich edycji jarmarku na Międzymurzu Barbakanu; dokładne daty 2026 ogłaszane jesienią." },
  { name:"Jarmark Bożonarodzeniowy w Krakowie", city:"Kraków", lat:50.0647, lng:19.945, start:"2026-11-27", end:"2027-01-01",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://kiermasze.com.pl", verified:false, note:"Przybliżony termin na wzór poprzednich edycji (koniec listopada–początek stycznia) na Rynku Głównym; dokładne daty 2026 ogłaszane jesienią." },
  { name:"Jarmark Wielkanocny w Krakowie", city:"Kraków", lat:50.0647, lng:19.945, start:"2027-03-18", end:"2027-03-28",
    category:"jarmark", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://kongregacja.pl", verified:false, estimated:true, note:"Przybliżony termin na ok. 1,5 tygodnia przed Wielkanocą (28 marca 2027) na Rynku Głównym, na wzór edycji 2026 (26.03–6.04)." },

  /* ===== INNE — rozszerzenie 2026-07-30 (research) ===== */
  { name:"Żagle Szczecin 2026", city:"Szczecin", lat:53.4298, lng:14.5929, start:"2026-08-14", end:"2026-08-16",
    category:"inne", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Największa morska impreza plenerowa Pomorza Zachodniego z koncertami gwiazd i ponad 100 atrakcjami nad Odrą." },
  { name:"Warsaw Stand-up Festival", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-09-16", end:"2026-09-16",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:null, verified:true, note:"Wieczór największych gwiazd polskiego stand-upu w Amfiteatrze w Parku Sowińskiego." },
  { name:"Festiwal Nauki w Warszawie", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-09-18", end:"2026-09-27",
    category:"inne", free:true, priceMin:null, pricePass:null, priceNote:null,
    website:"https://festiwalnauki.edu.pl", verified:true, note:"Jubileuszowa 30. edycja największego w Polsce wydarzenia popularyzującego naukę." },
  { name:"Międzynarodowy Festiwal Komiksu i Gier", city:"Łódź", lat:51.7592, lng:19.456, start:"2026-09-19", end:"2026-09-20",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://komiksfestiwal.com", verified:true, note:"37. edycja największego święta komiksu i gier w Polsce, w Atlas Arenie i Sport Arenie." },
  { name:"Międzynarodowy Festiwal Ciało/Umysł", city:"Warszawa", lat:52.2297, lng:21.0122, start:"2026-10-08", end:"2026-10-11",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://cialoumysl.pl", verified:true, note:"26. edycja festiwalu sztuki tańca i performansu w STUDIO teatrgaleria." },
  { name:"Game Industry Conference", city:"Poznań", lat:52.4064, lng:16.9252, start:"2026-10-21", end:"2026-10-24",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:"Bilety konferencyjne od ok. 600 zł, towarzyszy Poznań Game Arena",
    website:"https://gic.gd", verified:true, note:"Największa w Polsce konferencja branży gier wideo, równolegle z Poznań Game Arena." },
  { name:"Festiwal Kultury Żydowskiej SIMCHA", city:"Wrocław", lat:51.1079, lng:17.0385, start:"2027-06-26", end:"2027-07-02",
    category:"inne", free:false, priceMin:null, pricePass:null, priceNote:null,
    website:"https://simcha.art.pl", verified:false, estimated:true, note:"Edycja 2026 odbyła się 27.06-3.07, termin 2027 przybliżony na podstawie poprzednich edycji." },

];
const FESTIWALE_UPDATED = "2026-07-30";
